### ISSUE TITLE
bash cli autocompletion is not installed

### ISSUE THREAD

**Issue by elico** [PacktPublishing/Preparing-for-the-Certified-OpenStack-Administrator-Exam#3]
I have tried to install the openstack client bash auto-completion using:
https://docs.openstack.org/python-openstackclient/pike/cli/command-objects/complete.html

But it didn't work since the `bash-completion` is not installed.
After installing using:
`sudo apt install bash-completion`
and reconnect again makes it work.

**Comment by ManikandanKurup-Packt** [comment]
@elico so I presume the issue is resolved now?

**Comment by elico** [comment]
@ManikandanKurup-Packt I wrote a solution.
